name: AccountSwitcher
options:
  bundleIdPrefix: com.blizzard
  deploymentTarget:
    iOS: "15.0"
  createIntermediateGroups: true
packages:
  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation.git
    from: 0.9.19
targets:
  AccountSwitcher:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - AccountSwitcher
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.blizzard.diablo.accountswitcher
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGN_ENTITLEMENTS: ""
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.0"
        IPHONEOS_DEPLOYMENT_TARGET: "15.0"
        ENABLE_BITCODE: NO
        INFOPLIST_FILE: AccountSwitcher/AccountSwitcher/Info.plist
        GENERATE_INFOPLIST_FILE: NO
    dependencies:
      - package: ZIPFoundation
